# Generated by Django 2.0.7 on 2018-08-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LEDThemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themeName', models.CharField(max_length=100)),
                ('themeId', models.IntegerField()),
                ('themeSNo', models.IntegerField()),
                ('themeType', models.IntegerField()),
                ('themeBrt', models.IntegerField()),
                ('themeSpd', models.IntegerField()),
                ('themeClr', models.CharField(max_length=8)),
                ('themeOption', models.CharField(max_length=100)),
            ],
        ),
    ]
