# Generated by Django 2.0.7 on 2018-08-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infinityroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledthemes',
            old_name='themeOption',
            new_name='themeOption_db',
        ),
    ]
