# Generated by Django 2.0.7 on 2018-08-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinityroom', '0002_auto_20180807_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedTheme', models.IntegerField()),
                ('tcp', models.BinaryField()),
                ('gvId', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ledthemes',
            name='enable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
