# Generated by Django 2.0.7 on 2018-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinityroom', '0004_auto_20180810_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvars',
            name='tcp_db',
            field=models.TextField(),
        ),
    ]
