# Generated by Django 2.1 on 2018-08-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinityroom', '0005_auto_20180810_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledthemes',
            name='themeSpdMax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ledthemes',
            name='themeSpdMin',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
