# Generated by Django 2.1 on 2018-08-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinityroom', '0006_auto_20180815_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('devId', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('devType', models.CharField(max_length=8)),
                ('target', models.CharField(max_length=8)),
                ('brt', models.IntegerField()),
                ('spd', models.IntegerField()),
                ('spdMax', models.IntegerField()),
                ('spdMin', models.IntegerField()),
                ('clr', models.CharField(max_length=8)),
                ('option_db', models.CharField(max_length=100)),
                ('enable', models.BooleanField()),
                ('state', models.BooleanField()),
                ('other_db', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myIp', models.CharField(max_length=20)),
                ('sys_ip_db', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='GlobalVars',
        ),
    ]
